### ISSUE TITLE
Cypress integration test block focusing issue

### ISSUE THREAD

**Issue by tiberiuichim** [eea/volto-slate#101]
https://gist.github.com/sneridagh/75212d81d8bbb28a49540bb5c69f2574

**Comment by tiberiuichim** [comment]
https://gist.github.com/sneridagh/75212d81d8bbb28a49540bb5c69f2574

**Comment by avoinea** [comment]
@tiberiuichim @sneridagh See https://github.com/eea/volto-slate/commit/98e7617ce3e3e7bfc866f9a9044ea28e20fbccd9 

Not sure if it was supposed to fail but I adapted it to pass :laughing:
