### ISSUE TITLE
Placeholder: "Enter some richtext..." -> "Type text..."

### ISSUE THREAD

**Issue by tisto** [eea/volto-slate#112]
volto-slate currently uses "Enter some richtext..." as placeholder. We should make this placeholder consistent with Volto/Draft and use "Type text...". This message also needs to be translated into the different languages that Volto currently supports.

I did not find the string in the volto-slate repo. Does this come from Slate directly?

**Comment by tiberiuichim** [comment]
https://github.com/eea/volto-slate/blob/master/src/blocks/Text/TextBlockEdit.jsx#L299

@tisto We've used the different placeholder to serve as a "marker" that we're dealing with slate instead of draft. Actually the whole addon needs i18n support, it doesn't have it right now, I think.

**Comment by tisto** [comment]
@tiberiuichim is this something we can create? I am happy to take care of the German translations. Though, we can not ship a system to a German client that has "Please enter some richtext..." all over the place. cc @sneridagh

**Comment by tisto** [comment]
@tiberiuichim ping :) Any news on this?

**Comment by tiberiuichim** [comment]
@tisto I've opened a PR here for this: https://github.com/eea/volto-slate/pull/119

There's some issues with the tests, I'm trying to track them. For some reason the whole build fails when I add babel.config.js
