### ISSUE TITLE
Clicking on bullet point / numbering icon does not remove bullets/numbering

### ISSUE THREAD

**Issue by tisto** [eea/volto-slate#122]
# StR

* as admin
* create document
* add bullet point list with two lines
* select second line and click on the "bullet point" icon in the Slate overlay
* -> nothing happens
* -> expected behavior: the bullet point styling goes away (same behavior as for bold, italic, headlines, quote, blockquote)

# Screenshot

![Add-Document (2)](https://user-images.githubusercontent.com/632105/126664338-e39aeb56-1b01-4319-ad50-c6d4d391798a.png)

**Comment by tiberiuichim** [comment]
Fixed by #124
