### ISSUE TITLE
Not able to click in table block and also pasting table from google docs and inserting links doesn't work

### ISSUE THREAD

**Issue by iFlameing** [eea/volto-slate#141]
@tiberiuichim when using the touchpad for clicking into table block I am not able to get the cursor in the table block. When I force click on the touchpad then I am able to get the cursor in table block.

**Comment by iFlameing** [comment]
@tiberiuichim  When I copied the table from google docs and try to add a link to the text it is giving me an error.

![Screenshot 2021-09-01 at 7 35 51 PM](https://user-images.githubusercontent.com/33936987/131685864-9e560863-1ee2-4e4f-ad41-bfc83f306675.png)

**Comment by tiberiuichim** [comment]
@iFlameing could you share with me the google doc that you have?

**Comment by iFlameing** [comment]
@tiberiuichim link of the google docs https://docs.google.com/document/d/1vlFbCo7hOiQkRE4yq4j08gLghJGtNj6a0suw_W7VXsw/edit?usp=sharing

**Comment by tiberiuichim** [comment]
@iFlameing give the develop branch a try

**Comment by iFlameing** [comment]
@tiberiuichim Now the pasting the table doesn't work.

Screenshot

<img width="924" alt="Screenshot 2021-09-08 at 6 07 46 PM" src="https://user-images.githubusercontent.com/33936987/132510554-c4a48042-0388-42f7-ab3f-dc30e8399dec.png">

**Comment by tiberiuichim** [comment]
@iFlameing that's because the table is no longer in the default, @avoinea will know more. 

Add the `tableButton` profile to be loaded, see https://github.com/eea/volto-slate/blob/aef31f14c599a8dd5fbc3d78de6772080142abb6/src/index.js#L75

**Comment by avoinea** [comment]
```
 addons: [
   "volto-slate:asDefault,tableButton"
]
```

**Comment by iFlameing** [comment]
@tiberiuichim @avoinea thank you

**Comment by iFlameing** [comment]
@avoinea @tiberiuichim I tried it yesterday and it is working but suddenly today it is not working. It is giving me error when I am adding tableButton.
```    "volto-slate:minimalDefault,simpleLink,tableButton",
```

```

Each addon has to provide a function applying its configuration to the projects configuration.
    at load (/Users/alokkumar/Documents/github/fzj-internet/private/var/folders/f4/4szxrlb153l60k2b7jdzzjl40000gn/T/tmp-32014-VaqJIP1VnxJt-.js:28:1)
    at Module../node_modules/@plone/volto/src/config/index.js (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/node_modules/@plone/volto/src/config/index.js:178:1)
    at __webpack_require__ (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/server.jsx (/Users/alokkumar/Documents/github/fzj-internet/build/server.js:69845:77)
    at __webpack_require__ (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/start-server.js (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/node_modules/@plone/volto/src/start-server.js:1:1)
    at __webpack_require__ (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/alokkumar/Documents/github/fzj-internet/build/webpack:/webpack/bootstrap:59:1)

````

**Comment by avoinea** [comment]
@iFlameing check your addons, you're not returning config within some of them.

**Comment by iFlameing** [comment]
@avoinea it is only giving me error when I am adding tableButton

**Comment by iFlameing** [comment]
otherwise it is working perfectly fine.

**Comment by avoinea** [comment]
@iFlameing or your Volto project is bringing another version of volto-slate (without `tableButton` profile).

Try to pin volto-slate to `3.0.0-alpha.0`

**Comment by iFlameing** [comment]
@avoinea I am using volto-slate by mrs developer and this is my code and I think it is the latest one 
```  "volto-slate": {
    "develop": false,
    "package": "volto-slate",
    "url": "git@github.com:eea/volto-slate.git",
    "https": "https://github.com/eea/volto-slate.git",
    "path": "src",
    "branch": "develop"
  }

**Comment by iFlameing** [comment]
@avoinea I don't have the table config in index.js in (node_modules)  that's why I am getting this error.

**Comment by avoinea** [comment]
@iFlameing told you. I will release 3.0.0 final today. To avoid this alpha stage issues :)

**Comment by iFlameing** [comment]
@avoinea ok

**Comment by iFlameing** [comment]
@tiberiuichim @avoinea I tried the latest version 3.0.1 and problem still persist. I am attaching the screencast for your reference.
Screencast


https://user-images.githubusercontent.com/33936987/133426749-1e6b579f-de0e-44f5-9119-663b2260178e.mp4

**Comment by iFlameing** [comment]
the sidebar does not open only when I am pasting the table from google docs. If I am creating the table by myself then I am able to do so.
    https://docs.google.com/document/d/1vlFbCo7hOiQkRE4yq4j08gLghJGtNj6a0suw_W7VXsw/edit?usp=sharing

**Comment by tiberiuichim** [comment]
@iFlameing give the develop branch a try now, I've replicated the problem and fixed it.

**Comment by iFlameing** [comment]
@tiberiuichim I tested the latest alpha release and it work like charm!
