### ISSUE TITLE
slate crashed when we paste a bold content in Bullet list and ordered list

### ISSUE THREAD

**Issue by iFlameing** [eea/volto-slate#163]
@tiberiuichim can you help me regarding this.

steps to reproduce.

1. in edit mode enter short text in a normal text field
2. mark the text as bullet list
3. press enter to get the second bullet
4. copy a text formatted in bold from a Word document or from a web page shown in your browser with CTRL-C
5. try to paste this with CTRL-V behind the second bullet
6. bold text will be pasted into a new text field
7. position cursor before the bold text and press delete key in order to merge bold text with the bullet list.
8. Error message occurs.

Screenshot
![list-elements-bold-italic-error](https://user-images.githubusercontent.com/33936987/135638131-24dc18f1-528c-4c9e-beb3-0b3c20e1a5d4.png)

**Comment by iFlameing** [comment]
@silviubogan I am still able to reproduce it. 
I have gone through the same steps which is mentioned above.
<img width="1433" alt="Screenshot 2021-11-01 at 4 24 48 PM" src="https://user-images.githubusercontent.com/33936987/139661119-bf2bbb47-183d-4afa-92d3-199209fc35a4.png">

**Comment by silviubogan** [comment]
Can you please try to reproduce the bug with the Volto-Slate branch `external-data-normalization`? Thanks.

**Comment by iFlameing** [comment]
@silviubogan the error is gone with `external-data-normalization` but I lost the formatting.

this is the screenshot after implementing the above steps.
![Screenshot 2021-11-01 at 7 44 37 PM](https://user-images.githubusercontent.com/33936987/139685933-00e2c74e-cf23-4a03-9b69-7a13d19764aa.png)

**Comment by silviubogan** [comment]
@iFlameing  With the latest commit in the `external-data-normalization` branch I cannot reproduce the bug. Could you try to recreate that Volto-Slate block from scratch, if you did not recently? It is possible that the bug is caused by other addons you have installed in Volto-Slate. What profiles of Volto-Slate do you use in your Volto project and what addons do you have installed over Volto-Slate?

**Comment by iFlameing** [comment]
@silviubogan I pulled the recent changes but I am still able to see the same `the above screenshot with error doesn't have the list order`. I am using this configuration `    "volto-slate:minimalDefault,simpleLink,tableButton",
`

**Comment by silviubogan** [comment]
@iFlameing The bug seems to be in the code specific to the profile `tableButton`, so if it is urgent, you can disable that profile from your configuration. I am investigating this bug right now. Thanks.

**Comment by silviubogan** [comment]
@iFlameing Sorry, it seems that the bug appears with the only profile `minimalDefault` too.

**Comment by silviubogan** [comment]
@iFlameing I've checked and this bug is solved in #181.

**Comment by iFlameing** [comment]
@silviubogan @tiberiuichim  @sneridagh  hey! I checked this and found out that now we don't get any error but the intended behavior is not there.  Now we can't paste the bold content in the bullet list.

steps to reproduce

1. in edit mode enter short text in a normal text field
2. mark the text as a bullet list
3. press enter to get the second bullet
4. copy a text formatted in bold from a Word document or from a web page shown in your browser with CTRL-C
5. try to paste this with CTRL-V behind the second bullet
6. bold text will be pasted into a new text field
7. position cursor before the bold text and press delete key in order to merge bold text with the bullet list.
8. the pasted things are gone. 

Intended behavior will be `it should be as a bullet list`.

**Comment by silviubogan** [comment]
@iFlameing I think this is solved in https://github.com/eea/volto-slate/pull/195.

**Comment by silviubogan** [comment]
@iFlameing I think that a Cypress test for this bug will be done in the following days.

**Comment by nileshgulia1** [comment]
> @iFlameing I think that a Cypress test for this bug will be done in the following days.

https://github.com/eea/volto-slate/pull/200
