### ISSUE TITLE
Pasting line breaks inside title and description blocks inserts line breaks

### ISSUE THREAD

**Issue by silviubogan** [eea/volto-slate#185]
And this is wrong at least because of the styling of the title block when it has multiple lines of content:

![image](https://user-images.githubusercontent.com/198924/141747478-53d49903-05a3-4ddc-9b85-eda79da86c7f.png)

**Comment by nileshgulia1** [comment]
@silviubogan Can you please provide an example content? I cannot reproduce it anymore.

**Comment by tiberiuichim** [comment]
when pasting inside the title block non-space whitespace + duplicated spaces should be stripped. This should be an extension of the Title block, not something that would be treated in the slate editor by default.

**Comment by nileshgulia1** [comment]
This could be handled on a project basis. These are the default plugins for now https://github.com/eea/volto-slate/blob/develop/src/editor/plugins/index.js
