### ISSUE TITLE
Tab navigation issue

### ISSUE THREAD

**Issue by avoinea** [eea/volto-slate#198]
https://user-images.githubusercontent.com/323385/143417438-90386a23-fc60-4d59-a9bc-dee289d23175.mp4

Block is not selected when using tab. Thus if you press enter at the end of text the cursor is not moved to the newly created slate block

**How to reproduce:**
* Click on Title
* Use tab key to go to the next block
* Use arrow keys to go to the end of the text
* Type Enter

**Comment by nileshgulia1** [comment]
Fixed in #195
