### ISSUE TITLE
Not able to add the block if the previous text is bold

### ISSUE THREAD

**Issue by iFlameing** [eea/volto-slate#208]
@tiberiuichim can you please look into this

Steps to reproduce.
1. Write some texts  and made them bold
2. Press enter
3. Now you are not able to add the new block

screencast

https://user-images.githubusercontent.com/33936987/145796269-7f3776e5-1a92-4a57-8c81-d48a4aae065c.mp4

**Comment by nileshgulia1** [comment]
@iFlameing I think this is fixed in latest release via https://github.com/eea/volto-slate/pull/203, Can you please try on develop branch?

**Comment by iFlameing** [comment]
@nileshgulia1 ok

**Comment by iFlameing** [comment]
It is fixed
