### ISSUE TITLE
Blank spaces text block not rendered in view

### ISSUE THREAD

**Issue by iFlameing** [eea/volto-slate#209]
@tiberiuichim 

Steps to reproduce

1. Go to edit page
2. write the title My page
3. on next text block write My first text block
4. on next text block put some blank by pressing `backspace`
5. on next block write end
6. go to view
7. the p tag with blank is not rendered

**Comment by tiberiuichim** [comment]
@iFlameing https://github.com/plone/volto/issues/1851

**Comment by nileshgulia1** [comment]
<img width="651" alt="Screenshot 2021-12-14 at 2 39 24 PM" src="https://user-images.githubusercontent.com/22280901/145967920-3b72d02e-7a12-43eb-b3ec-8b4b9718d97a.png">

okay so, in view we have it like this. The multiple spaces inside the middle `<p>` block resolves to single in view.

**Comment by iFlameing** [comment]
@tiberiuichim @nileshgulia1 as the above screenshot shows that we have an empty rendered p tag. But due to margin collapse we didn't get the margin-top of the empty p tag and it is not solvable.
