### ISSUE TITLE
Installation: dependency 'volto-object-widget'

### ISSUE THREAD

**Issue by ksuess** [eea/volto-slate#49]
Hi! First of all: Slate is cool. And this, your Slate integration rocks. 
- pasting text by creating multiple blocks is magnificent
- the play of Slate with ElasticSearch is a lot easier than that of DraftJS (thanks for the plaintext value!)
- the widget for setting links is really comfortable
- well, the response on selecting text is a bit sluggish 

I switch to Slate.

This is what I think is also necessary to install eea/volto-slate:

```
"addons": [
  "@eeacms/volto-object-widget"
],

"dependencies": {
  "@eeacms/volto-object-widget": "^1.0.0"
}
```

It's not enough to follow this instruction of [README.txt](https://github.com/eea/volto-slate):

_If you already have a volto project, just update `package.json`:_

 ```JSON
 "addons": [
     "volto-slate:asDefault"
 ],

 "dependencies": {
     "volto-slate": "^1.0.0"
 }
 ```

Thank you for taking time for this!

**Comment by avoinea** [comment]
@ksuess Thank you! I will update docs. 

I found that it also needs `@eeacms/volto-blocks-form`

**Comment by avoinea** [comment]
@ksuess Fixed. See (README](https://github.com/eea/volto-slate#getting-started)
