### ISSUE TITLE
After going through steps in DEVELOP.md I get an empty Volto home page

### ISSUE THREAD

**Issue by silviubogan** [eea/volto-slate#53]
![image](https://user-images.githubusercontent.com/198924/103211685-8cc62680-4911-11eb-9d7a-c4c94397717d.png)

(note: My Page is an attempt to create a Volto Page that also failed in some way)

I think it is a bug in plone.docker since that is where the home page I am used to comes from.

When I try to create a page, I do not get the block editor form I am used to but a properties page without Volto Slate installed in it:

![image](https://user-images.githubusercontent.com/198924/103211863-0231f700-4912-11eb-98d7-95e506ecbaf5.png)

**Comment by avoinea** [comment]
Add `-e PROFILES="profile-plone.restapi:blocks"` to the docker run command like:
```
$ docker run -d --name plone -p 8080:8080 -e SITE=Plone -e PROFILES="profile-plone.restapi:blocks" plone
```
Or you can manually add the `Blocks` behavior within:
* Site Setup > Dexterity Content Types > Page > **Behaviors Tab**
